Repository FernandezAneena/CITS5505-Exercise-Tracker-Project, pull requests merged in 2025-05, with the labels that each got.

#54 Enhance Auth UI: Styled Login, Register, and Forgot Password Pages
  app/.DS_Store
  app/static/css/style.css
  app/templates/base.html
  app/templates/forgot_password.html
  app/templates/index.html
  app/templates/input.html
  app/templates/login.html
  app/templates/register.html
  app/templates/share.html
  app/templates/visualise.html
  app/templates/workout_plan.html
  instance/dbase.db
Labels: enhancement, frontend

#58 Add Workout Logging Feature
  app/app.py
  app/database.py
  app/static/js/scripts.js
  app/templates/dashboard.html
  instance/dbase.db
  migrations/versions/6f4c1b1a67ad_add_weeklyplan_and_workoutlog_models.py
  migrations/versions/7a5ec745e1fd_initial_migration.py
  migrations/versions/d859d14a9153_make_start_date_nullable.py
Labels: enhancement, backend

#67 Integrate Flask-Login for user authentication
  app/app.py
  app/database.py
  instance/dbase.db
Labels: enhancement, flask

#69 Add friend search and leaderboard functionality
  app/app.py
  app/database.py
  app/static/css/dashboard.css
  app/static/js/friends.js
  app/templates/dashboard.html
  migrations/versions/91394359c9d4_add_friendship_table.py
Labels: frontend, backend

#79 feat: Upgrade all major forms to Flask-WTF with CSRF protection and preserved styling
  app/app.py
  app/forms.py
  app/static/css/style.css
  app/static/js/scripts.js
  app/templates/base.html
  app/templates/dashboard.html
  app/templates/login.html
  app/templates/register.html
  instance/dbase.db
  tests/test_auth.py
Labels: enhancement, auth, setup, flask

#80 Refactor: Restructure project using app factory and blueprints
  app/__init__.py
  app/app.py
  app/blueprints.py
  app/config.py
  app/database.py
  app/extensions.py
  app/routes.py
  app/templates/base.html
  app/templates/dashboard.html
  app/templates/forgot_password.html
  app/templates/login.html
  app/templates/register.html
  instance/dbase.db
  project-signup.py
Labels: enhancement, backend, auth

#82 Update auth tests and add friend functionality tests
  tests/test_auth.py
  tests/test_friends.py
Labels: unit test

#84 Refactor password recovery workflow to use Flask-WTF forms
  app/forms.py
  app/routes.py
  app/templates/forgot_password.html
  instance/dbase.db
Labels: enhancement, backend, auth

#88 Add Selenium Tests for Login and Register Pages
  app/config.py
  app/templates/login.html
  app/templates/register.html
  tests/test_selenium_login.py
  tests/test_selenium_register.py
Labels: auth, SeleniumTesting

#90 Add Selenium tests for friend functionality
  tests/test_selenium_friends.py
Labels: SeleniumTesting

#92 Refactor: Clean Up UI Structure and Styling
  app/app.py
  app/forms.py
  app/routes.py
  app/static/js/Register.js
  app/static/js/scripts.js
  app/static/js/visualise.js
  app/templates/about.html
  app/templates/dashboard.html
  app/templates/forgot_password.html
  app/templates/login.html
  app/templates/register.html
  instance/dbase.db
Labels: enhancement

#93 Add requirements.txt file for dependency management
  requirements.txt
Labels: setup

#94 docs: Update README with latest project structure and instructions
  README.md
Labels: documentation

#96 Final UI
  app/static/css/style.css
  app/static/images/fitness-hero.jpg
  app/templates/index.html
  instance/dbase.db
Labels: frontend
